import React, { createContext, useContext, useState, useEffect } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

type LanguageType = 'id' | 'en';

interface LanguageContextType {
  language: LanguageType;
  setLanguage: (lang: LanguageType) => void;
  t: (key: string) => string;
}

const translations = {
  id: {
    home: 'Beranda',
    gallery: 'Galeri',
    agenda: 'Agenda',
    profile: 'Profil',
    collections: 'Koleksi Pribadi',
    savedGallery: 'Galeri Tersimpan',
    savedDesc: 'Lihat daftar foto & video yang Anda simpan',
    theme: 'Tampilan Tema',
    light: 'Terang',
    dark: 'Gelap',
    system: 'Sistem',
    security: 'Keamanan Data',
    protection: 'Status Perlindungan',
    protected: 'Data terlindungi enkripsi',
    safe: 'Aman',
    adminMenu: 'Administrator',
    manageAdmin: 'Kelola Data Admin',
    manageAdminDesc: 'Tambah, ubah, dan hapus data pusaka',
    others: 'Lainnya',
    helpCenter: 'Pusat Layanan',
    helpCenterDesc: 'Tanya jawab & bantuan pengguna',
    terms: 'Syarat Ketentuan',
    termsDesc: 'Regulasi dan kebijakan data',
    appInfo: 'Informasi Aplikasi',
    appInfoDesc: 'Versi 1.0.0 (Release)',
    logout: 'Keluar Akun',
    editProfile: 'Ubah Profil',
    editPassword: 'Ubah Sandi',
    language: 'Pilihan Bahasa',
    morning: 'Selamat Pagi 🌅',
    afternoon: 'Selamat Siang ☀️',
    evening: 'Selamat Sore 🌇',
    night: 'Selamat Malam 🌙',
    exploreHeritage: 'Jelajahi Warisan Budaya',
    exploreNow: 'Jelajahi Sekarang',
    heroTitle: 'Temukan Warisan\nRaja Ali Haji',
    heroSubtitle: 'Pusaka Pulau Penyengat, Kepulauan Riau',
    searchPlaceholder: 'Cari naskah, artefak, atau sejarah...',
    upcomingEvents: 'Agenda Mendatang',
    seeAll: 'Lihat Semua',
    exploreNearby: 'Eksplorasi Terdekat',
    all: 'Semua',
    artifactType: 'Artefak',
    history: 'Sejarah',
    manuscript: 'Naskah',
    monument: 'Monumen',
    object: 'Benda',
    audio: 'Audio',
    loadingData: 'Memuat data sejarah...',
    errorData: 'Gagal memuat data sejarah.',
    emptyData: 'Belum ada data sejarah yang tersedia.',
    mapTourPath: 'Jalur Tur Edukasi',
    mapLoadingLocation: 'Memuat lokasi...',
    mapSitesFound: '{count} situs warisan ditemukan',
    mapLoadingSites: 'Memuat situs warisan...',
    mapYear: 'Tahun {year}',
    mapViewDetail: 'Lihat Detail Lengkap',
    mapStartExploration: 'Mulai Eksplorasi',
    mapTapPrompt: 'Ketuk salah satu titik di peta untuk melihat detail situs warisan.',
    mapNoSites: 'Belum ada situs dengan koordinat. Tambahkan melalui Panel Admin.',
    galleryAndMedia: 'Galeri & Media',
    galleryDesc: 'Dengarkan mahakarya & jelajahi koleksi foto pusaka.',
    searchMedia: 'Cari foto, video, atau musik...',
    playlist: 'Daftar Putar',
    noAudio: 'Belum ada audio yang diunggah.',
    visualGallery: 'Galeri Visual',
    gallerySubtitle: '{count} koleksi foto & video artefak bersejarah',
    noVisualMedia: 'Belum ada media visual.',
    video: 'Video',
    photo: 'Foto',
    untitled: 'Tanpa Judul',
    loadMore: 'Muat Lebih Banyak',
    videoPlayer: 'Pemutar Video',
    youtubeRestriction: 'Video ini dari YouTube dan dibatasi untuk diputar di dalam aplikasi.',
    watchOnYoutube: 'Tonton di YouTube',
    islandLocation: 'Pulau Penyengat, Kepulauan Riau',
    booksHeroTitle: 'Pustaka Nusantara',
    booksHeroSub: 'Eksplorasi arsip naskah kuno dan literatur warisan sejarah maritim Kepulauan Riau.',
    booksCollectionLabel: 'Koleksi',
    booksAvailableLabel: 'Tersedia',
    booksSearch: 'Cari judul buku atau naskah...',
    booksLoading: 'Memuat perpustakaan...',
    booksLoadingMore: 'Memuat lebih banyak...',
    booksEmptyTitle: 'Belum ada buku',
    booksEmptyDesc: 'Admin belum menambahkan buku ke perpustakaan.',
    booksUnknownAuthor: 'Penulis tidak diketahui',
    booksSynopsis: 'Sinopsis',
    booksReadBtn: 'Baca / Buka',
    booksCloseBtn: 'Tutup',
    booksFileNotAvailable: 'File Belum Tersedia',
    booksFileNotUploaded: 'Dokumen untuk buku ini belum diunggah oleh admin.',
    agendaNoDate: 'Tanggal belum ditentukan',
    agendaEnded: 'Acara Telah Berakhir',
    agendaDaysLeft: '{days} hari {hours}j {minutes}m {seconds}d',
    agendaHoursLeft: '{hours}j {minutes}m {seconds}d',
    success: 'Sukses',
    agendaAdded: 'Agenda berhasil ditambahkan ke kalender perangkat Anda!',
    failed: 'Gagal',
    agendaNoCalendar: 'Tidak menemukan kalender default di perangkat Anda.',
    permissionDenied: 'Izin Ditolak',
    agendaPermission: 'Aplikasi butuh izin untuk menyimpan acara ke kalender.',
    error: 'Error',
    agendaErrorAdd: 'Terjadi kesalahan saat menambahkan agenda ke kalender.',
    remindMe: 'Ingatkan',
    agendaHeader: 'Agenda & Acara',
    agendaHeroTitle: 'Jadwal Kebudayaan',
    agendaHeroSub: 'Ikuti terus perkembangan festival, kajian, dan peringatan sejarah di RAHVerse.',
    agendaLoading: 'Memuat jadwal agenda...',
    agendaEmptyTitle: 'Belum ada agenda',
    agendaEmptyDesc: 'Saat ini tidak ada acara mendatang yang dijadwalkan.',
    collectionsEmptyTitle: 'Belum Ada Koleksi',
    collectionsEmptyDesc: 'Foto atau video yang Anda simpan akan muncul di sini sebagai koleksi pribadi.',
    collectionsExploreBtn: 'Jelajahi Galeri',
    catalogHeader: 'Katalog & Ensiklopedia',
    catalogDesc: 'Jelajahi museum virtual peninggalan pusaka dan tradisi bahari Nusantara.',
    catalogSearch: 'Cari keris, perahu, monumen...',
    catalogLoading: 'Menyusun Katalog...',
    catalogKamusEmpty: 'Istilah tidak ditemukan di kamus.',
    catalogEmpty: 'Tidak ada peninggalan yang cocok.',
    catalogYearEra: 'Tahun / Era',
    catalogLocation: 'Lokasi Penyimpanan',
    catalogDefaultLocation: 'Museum Bahari / Koleksi Pribadi',
    catalogHistoryDesc: 'Sejarah & Deskripsi',
    catalogCloseModal: 'Tutup',
    tabHome: 'Beranda',
    tabMap: 'Peta',
    tabGallery: 'Galeri',
    tabCatalog: 'Katalog',
    tabBooks: 'Buku',
    artLoading: 'Memuat data...',
    artNotFound: 'Data tidak ditemukan.',
    artBack: 'Kembali',
    artNoDesc: 'Belum ada deskripsi untuk peninggalan bersejarah ini.',
    artLocationNotMarked: 'Lokasi belum ditandai',
    artUnknownYear: 'Tidak diketahui',
    artOpenStatus: 'Tersedia di Tempat Penyimpanan / Museum',
    artOpen24H: 'Terbuka 24 Jam (Area Publik)',
    artOpenSchedule: 'Buka Mengikuti Jadwal Operasional',
    artDescTitle: 'Deskripsi',
    artReadMore: 'Baca Selengkapnya',
    artHide: 'Sembunyikan',
    artInfoTitle: 'Informasi',
    artType: 'Tipe',
    artYear: 'Tahun',
    artAuthor: 'Penulis',
    artLocation: 'Lokasi',
    artCoordsAvailable: 'Koordinat Tersedia',
    artAudioSection: '🎵 Syair & Audio',
    artMapSection: 'Peta Lokasi',
    artOpenMap: 'Buka di Peta',
    artPhotoGallery: 'Galeri Foto',
    artPhotos: '{count} foto',
    artGalleryMedia: 'Galeri & Media',
    artEmptyGallery: 'Belum ada foto atau audio untuk artefak ini',
    artRelated: 'Peninggalan Serupa',

    helpCenterTitle: 'Pusat Layanan',
    helpHeroTitle: 'Ada yang bisa kami bantu?',
    helpHeroSub: 'Cari jawaban dari pertanyaan Anda di bawah ini atau hubungi dukungan admin.',
    helpSearchPlaceholder: 'Cari bantuan...',
    helpCatAll: 'Semua',
    helpCatGeneral: 'Umum',
    helpCatAccount: 'Akun',
    helpCatBooks: 'Buku',
    helpCatGallery: 'Galeri',
    helpPopular: 'Pertanyaan Populer',
    helpEmpty: 'Pertanyaan tidak ditemukan.',
    helpContactTitle: 'Belum menemukan jawaban?',
    helpContactSub: 'Hubungi pusat admin kami secara langsung melalui jalur di bawah.',
    faq1Q: 'Bagaimana cara mengubah profil saya?',
    faq1A: "Masuk ke halaman Profil, ketuk tombol 'Ubah Profil' di bagian atas, kemudian isi nama lengkap, nomor telepon, atau bio baru Anda dan ketuk 'Simpan Perubahan'.",
    faq2Q: 'Mengapa gambar/audio pusaka tidak muncul?',
    faq2A: 'Pastikan koneksi internet Anda stabil. Aplikasi RAHVerse memuat media langsung dari database cloud Supabase. Jika masalah berlanjut, silakan hapus cache aplikasi atau restart perangkat.',
    faq3Q: 'Bagaimana cara membaca buku digital di RAHVerse?',
    faq3A: "Pergi ke tab 'Buku', ketuk buku yang ingin Anda baca, lalu ketuk tombol 'Baca Buku' untuk membuka viewer PDF bawaan kami.",
    faq4Q: 'Apakah aplikasi RAHVerse gratis digunakan?',
    faq4A: 'Ya, aplikasi RAHVerse sepenuhnya gratis dan ditujukan untuk tujuan edukasi, pelestarian budaya, serta pariwisata bahari Nusantara.',
    faq5Q: 'Bagaimana cara mengganti kata sandi akun?',
    faq5A: "Masuk ke halaman Profil, ketuk tombol 'Ubah Sandi', masukkan kata sandi lama Anda beserta kata sandi baru yang ingin Anda buat, lalu tekan 'Perbarui Sandi'.",

    termsHeaderTitle: 'Syarat & Ketentuan',
    termsTitle: 'Kebijakan Penggunaan',
    termsLastUpdated: 'Terakhir diperbarui: 6 Juni 2026',
    termsIntro: 'Selamat datang di RAHVerse! Halaman Syarat & Ketentuan ini mengatur akses dan penggunaan Anda terhadap aplikasi seluler RAHVerse (selanjutnya disebut "Aplikasi").',
    termsS1Title: '1. Penggunaan Aplikasi',
    termsS1Desc: 'Aplikasi RAHVerse disediakan hanya untuk tujuan edukasi budaya, pelestarian warisan pusaka bahari, serta navigasi/pariwisata. Anda setuju untuk menggunakan aplikasi ini dengan bijak dan mematuhi peraturan hukum yang berlaku di Indonesia.',
    termsS2Title: '2. Akun & Keamanan Data',
    termsS2Desc: 'Saat Anda mendaftar atau menggunakan akun Anda di RAHVerse, Anda bertanggung jawab penuh atas kerahasiaan kredensial login Anda. Database kami menggunakan enkripsi standar industri (Supabase Auth) untuk memastikan perlindungan terhadap data pribadi Anda.',
    termsS3Title: '3. Hak Kekayaan Intelektual',
    termsS3Desc: 'Seluruh konten yang terdapat di dalam aplikasi ini, termasuk namun tidak terbatas pada data pusaka, artikel sejarah, buku digital (PDF), rekaman audio/lagu rakyat, dan antarmuka desain grafis merupakan hak milik RAHVerse atau kontributor berlisensi.',
    termsS4Title: '4. Kebijakan Privasi',
    termsS4Desc: 'Kami tidak menjual atau membagikan data profil pribadi Anda (seperti nama lengkap, nomor telepon, dan bio) ke pihak ketiga. Data ini murni digunakan demi keperluan personalisasi pengalaman menjelajahi RAHVerse.',
    termsS5Title: '5. Modifikasi & Pembaruan Layanan',
    termsS5Desc: 'Kami berhak untuk mengubah atau menghentikan sebagian atau seluruh fitur aplikasi kapan pun tanpa pemberitahuan terlebih dahulu demi pembaruan sistem dan keamanan yang lebih baik.',
    termsFootnote: 'Dengan menggunakan Aplikasi RAHVerse, Anda dianggap telah menyetujui seluruh ketentuan yang tercantum di atas. Jika Anda tidak menyetujui ketentuan ini, Anda dipersilakan untuk tidak menggunakan aplikasi ini.',

    infoHeaderTitle: 'Informasi Aplikasi',
    infoVersion: 'Versi 1.0.0 (Build 26)',
    infoTagline: 'Warisan Budaya & Pusaka Bahari Nusantara',
    infoLabelDev: 'Pengembang',
    infoValueDev: 'Tim RAHVerse',
    infoLabelRelease: 'Rilis Pertama',
    infoValueRelease: 'Juni 2026',
    infoLabelFramework: 'Kerangka Kerja',
    infoLabelDB: 'Database Cloud',
    infoCopyright: '© 2026 RAHVerse. Hak Cipta Dilindungi.',
    infoSubCopyright: 'Dibuat dengan rasa cinta terhadap warisan bahari Indonesia.',

    adminPanel: 'Panel Admin',
    adminExit: 'Keluar',
    adminAdd: 'Tambah Data',
    adminSave: 'Simpan Perubahan',
    adminCancel: 'Batal',
    adminDelete: 'Hapus',
    adminEdit: 'Edit',
    adminConfirmDel: 'Apakah Anda yakin ingin menghapus data ini?',
    adminSuccess: 'Sukses',
    adminError: 'Gagal',
    adminLoading: 'Memuat data...',
    adminEmpty: 'Data tidak ditemukan',
    adminSearch: 'Cari data...',

    notifTitle: 'Notifikasi',
    notifLoading: 'Memuat notifikasi...',
    notifEmptyTitle: 'Belum ada notifikasi',
    notifEmptyDesc: 'Semua pembaruan dari admin akan muncul di sini.',
    notifDelete: 'Hapus',
    notifClearAlertTitle: 'Bersihkan Notifikasi',
    notifClearAlertDesc: 'Hapus semua notifikasi ini dari layar Anda?',
    notifClearCancel: 'Batal',
    notifClearConfirm: 'Ya, Bersihkan',
    notifJustNow: 'Baru saja',
    notifMinutesAgo: 'menit lalu',
    notifHoursAgo: 'jam lalu',
    notifDaysAgo: 'hari lalu',

    resetTitle: 'Kata Sandi Baru',
    resetSub: 'Silakan masukkan kata sandi baru untuk akun Anda.',
    resetNewPass: 'Kata sandi baru',
    resetConfirmPass: 'Konfirmasi kata sandi',
    resetSaveBtn: 'Simpan Kata Sandi',
    resetErrEmpty: 'Semua kolom wajib diisi.',
    resetErrMatch: 'Kata sandi tidak cocok.',
    resetErrLength: 'Kata sandi minimal 6 karakter.',
    resetSuccessTitle: 'Berhasil!',
    resetSuccessDesc: 'Kata sandi Anda berhasil diperbarui. Silakan masuk dengan kata sandi baru.',
    resetFailTitle: 'Gagal',

    profModalEditTitle: 'Ubah Profil',
    profModalFullName: 'Nama Lengkap',
    profModalFullNamePlaceholder: 'Ketik nama lengkap...',
    profModalPhone: 'Nomor Handphone',
    profModalPhonePlaceholder: 'Ketik nomor telpon aktif...',
    profModalBio: 'Informasi Singkat (Bio)',
    profModalBioPlaceholder: 'Tambahkan informasi singkat...',
    profModalSave: 'Simpan Perubahan',
    profModalPassTitle: 'Perbarui Sandi',
    profModalOldPass: 'Sandi Lama',
    profModalOldPassPlaceholder: 'Ketik sandi saat ini...',
    profModalNewPass: 'Sandi Baru',
    profModalNewPassPlaceholder: 'Ketik sandi baru...',
    profModalConfirmPass: 'Konfirmasi Sandi Baru',
    profModalConfirmPassPlaceholder: 'Ketik ulang sandi baru...',
    profModalPassUpdate: 'Perbarui Sandi',

    loginTabIn: 'Masuk',
    loginTabUp: 'Daftar',
    loginErrEmailPass: 'Email dan kata sandi wajib diisi.',
    loginErrAllField: 'Semua kolom wajib diisi.',
    loginErrMatch: 'Kata sandi tidak cocok.',
    loginErrLength: 'Kata sandi minimal 6 karakter.',
    loginRegSuccessTitle: 'Pendaftaran Berhasil!',
    loginRegSuccessDesc: 'Akun berhasil dibuat. Silakan cek email Anda untuk konfirmasi, lalu masuk.',
    loginResetReq: 'Silakan masukkan alamat email Anda untuk mereset kata sandi.',
    loginResetSentTitle: 'Email Terkirim',
    loginResetSentDesc: 'Tautan reset kata sandi telah dikirim. Silakan periksa email Anda.',
    
    loginErrInvalidCred: 'Email atau kata sandi salah.',
    loginErrNotConf: 'Email belum dikonfirmasi. Cek kotak masuk Anda.',
    loginErrAlreadyReg: 'Email ini sudah terdaftar. Silakan masuk.',
    loginErrWeakPass: 'Kata sandi terlalu lemah.',
    loginErrInvalidEmail: 'Format email tidak valid.',
    loginErrNotFound: 'Email tidak terdaftar di sistem kami.',
    
    loginWelcome: 'Selamat Datang,',
    loginWelcomeSub: 'Masuk untuk melanjutkan',
    loginJoin: 'Bergabung dengan RAHVerse,',
    loginJoinSub: 'Buat akun baru untuk mulai',
    
    loginFullName: 'Nama Lengkap',
    loginFullNamePlace: 'Ketik nama lengkap...',
    loginEmail: 'Alamat Email',
    loginEmailPlace: 'contoh@email.com',
    loginPass: 'Kata Sandi',
    loginPassPlace: 'Ketik kata sandi...',
    loginConfirmPass: 'Konfirmasi Sandi',
    loginConfirmPassPlace: 'Ketik ulang kata sandi...',
    
    loginForgot: 'Lupa kata sandi?',
    loginGuest: 'Lanjutkan sebagai Tamu',

    loginWelcome2: 'Selamat Kembali',
    loginWelcomeSub2: 'Masuk untuk mengakses koleksi naskah sejarah.',
    loginJoin2: 'Buat Akun Baru',
    loginJoinSub2: 'Bergabunglah dan jelajahi warisan budaya Melayu.',
    loginFullName2: 'Nama Lengkap',
    loginEmail2: 'Alamat Surel (Email)',
    loginPass2: 'Kata Sandi',
    loginConfirmPass2: 'Konfirmasi Kata Sandi',
    loginSubmitIn: 'Masuk Akun',
    loginSubmitUp: 'Daftar Sekarang',
    loginOr: 'ATAU',

    galTitle: 'Galeri Visual',
    galSub: 'Jelajahi visualisasi mendalam dari warisan Melayu.',
    galSearch: 'Cari koleksi...',
    galTabAll: 'Semua',
    galTabVisual: 'Visual',
    galTabMusic: 'Musik',
    galExplore: 'Eksplorasi Mendalam',
    galLatest: 'Koleksi Terbaru',
    galEmptyTitle: 'Belum ada koleksi',
    galEmptyDesc: 'Belum ada koleksi galeri di RAHVerse.',
    galNoDesc: 'Tidak ada deskripsi untuk foto ini.',
    galNoDescVideo: 'Tidak ada deskripsi untuk video ini.',
    galDescLbl: 'Deskripsi',
    galTypePhoto: 'Foto',
    galTypeVideo: 'Video',
    galTypeMusic: 'Musik',
    galUntitled: 'Tanpa Judul',
    galZoomBtn: 'Perbesar',

    galVideoPlayer: 'Pemutar Video',
    galWatchYT: 'Tonton di YouTube',
    galYTAlert: 'Video ini dari YouTube dan dibatasi untuk diputar di dalam aplikasi.',
    galPresentTime: 'Masa Kini',

    
    // Music Player Modal
    galPlayNow: 'Dengarkan Sekarang',
    galLyrics: 'Lirik Audio',
    galAbout: 'Tentang Artefak',
    galNext: 'Putar Berikutnya',
    galNoAudio: 'Belum ada audio terkait artefak ini.',
    galExploreArtifact: 'Eksplor Artefak Ini',
    galAnalyzedAI: 'Dianalisis oleh AI',
    galAnalyzedDesc: 'Penjelasan AI mengenai konteks lirik audio.',
    galExplanation: 'Penjelasan Mendalam',










  },
  en: {
    home: 'Home',
    gallery: 'Gallery',
    agenda: 'Events',
    profile: 'Profile',
    collections: 'My Collection',
    savedGallery: 'Saved Gallery',
    savedDesc: 'View your saved photos & videos',
    theme: 'Theme Display',
    light: 'Light',
    dark: 'Dark',
    system: 'System',
    security: 'Data Security',
    protection: 'Protection Status',
    protected: 'Data protected by encryption',
    safe: 'Safe',
    adminMenu: 'Administrator',
    manageAdmin: 'Manage Admin Data',
    manageAdminDesc: 'Add, edit, and delete heritage data',
    others: 'Others',
    helpCenter: 'Help Center',
    helpCenterDesc: 'Q&A & user support',
    terms: 'Terms & Conditions',
    termsDesc: 'Regulations and data policy',
    appInfo: 'App Information',
    appInfoDesc: 'Version 1.0.0 (Release)',
    logout: 'Log Out',
    editProfile: 'Edit Profile',
    editPassword: 'Change Password',
    language: 'Language Selection',
    morning: 'Good Morning 🌅',
    afternoon: 'Good Afternoon ☀️',
    evening: 'Good Evening 🌇',
    night: 'Good Night 🌙',
    exploreHeritage: 'Explore Heritage',
    exploreNow: 'Explore Now',
    heroTitle: 'Discover the Heritage\nof Raja Ali Haji',
    heroSubtitle: 'Pusaka of Penyengat Island, Riau',
    searchPlaceholder: 'Search manuscripts, artifacts...',
    upcomingEvents: 'Upcoming Events',
    seeAll: 'See All',
    exploreNearby: 'Explore Nearby',
    all: 'All',
    artifactType: 'Artifact',
    history: 'History',
    manuscript: 'Manuscript',
    monument: 'Monument',
    object: 'Object',
    audio: 'Audio',
    loadingData: 'Loading historical data...',
    errorData: 'Failed to load historical data.',
    emptyData: 'No historical data available.',
    mapTourPath: 'Educational Tour Path',
    mapLoadingLocation: 'Loading locations...',
    mapSitesFound: '{count} heritage sites found',
    mapLoadingSites: 'Loading heritage sites...',
    mapYear: 'Year {year}',
    mapViewDetail: 'View Full Details',
    mapStartExploration: 'Start Exploring',
    mapTapPrompt: 'Tap on any pin on the map to view heritage site details.',
    mapNoSites: 'No sites with coordinates available. Add them via Admin Panel.',
    galleryAndMedia: 'Gallery & Media',
    galleryDesc: 'Listen to masterpieces & explore heritage photo collections.',
    searchMedia: 'Search photos, videos, or music...',
    playlist: 'Playlist',
    noAudio: 'No audio uploaded yet.',
    visualGallery: 'Visual Gallery',
    gallerySubtitle: '{count} photo & video collections of historical artifacts',
    noVisualMedia: 'No visual media yet.',
    video: 'Video',
    photo: 'Photo',
    untitled: 'Untitled',
    loadMore: 'Load More',
    videoPlayer: 'Video Player',
    youtubeRestriction: 'This video is from YouTube and playback is restricted within the app.',
    watchOnYoutube: 'Watch on YouTube',
    islandLocation: 'Penyengat Island, Riau Archipelago',
    booksHeroTitle: 'Nusantara Library',
    booksHeroSub: 'Explore ancient manuscripts and maritime heritage literature of the Riau Archipelago.',
    booksCollectionLabel: 'Collections',
    booksAvailableLabel: 'Available',
    booksSearch: 'Search books or manuscripts...',
    booksLoading: 'Loading library...',
    booksLoadingMore: 'Loading more...',
    booksEmptyTitle: 'No books yet',
    booksEmptyDesc: 'Admin has not added any books to the library.',
    booksUnknownAuthor: 'Unknown Author',
    booksSynopsis: 'Synopsis',
    booksReadBtn: 'Read / Open',
    booksCloseBtn: 'Close',
    booksFileNotAvailable: 'File Not Available',
    booksFileNotUploaded: 'The document for this book has not been uploaded by the admin.',
    agendaNoDate: 'Date not yet determined',
    agendaEnded: 'Event Has Ended',
    agendaDaysLeft: '{days} days {hours}h {minutes}m {seconds}s',
    agendaHoursLeft: '{hours}h {minutes}m {seconds}s',
    success: 'Success',
    agendaAdded: 'Agenda successfully added to your device calendar!',
    failed: 'Failed',
    agendaNoCalendar: 'Default calendar not found on your device.',
    permissionDenied: 'Permission Denied',
    agendaPermission: 'App requires permission to save events to the calendar.',
    error: 'Error',
    agendaErrorAdd: 'An error occurred while adding the agenda to the calendar.',
    remindMe: 'Remind Me',
    agendaHeader: 'Agenda & Events',
    agendaHeroTitle: 'Cultural Schedule',
    agendaHeroSub: 'Keep up with the development of festivals, studies, and historical commemorations in RAHVerse.',
    agendaLoading: 'Loading agenda schedule...',
    agendaEmptyTitle: 'No agendas yet',
    agendaEmptyDesc: 'There are currently no upcoming events scheduled.',
    collectionsEmptyTitle: 'No Collections Yet',
    collectionsEmptyDesc: 'Photos or videos you save will appear here as your personal collection.',
    collectionsExploreBtn: 'Explore Gallery',
    catalogHeader: 'Catalog & Encyclopedia',
    catalogDesc: 'Explore the virtual museum of Nusantara maritime heritage and traditions.',
    catalogSearch: 'Search kris, boats, monuments...',
    catalogLoading: 'Compiling Catalog...',
    catalogKamusEmpty: 'Term not found in the dictionary.',
    catalogEmpty: 'No matching artifacts found.',
    catalogYearEra: 'Year / Era',
    catalogLocation: 'Storage Location',
    catalogDefaultLocation: 'Maritime Museum / Private Collection',
    catalogHistoryDesc: 'History & Description',
    catalogCloseModal: 'Close',
    tabHome: 'Home',
    tabMap: 'Map',
    tabGallery: 'Gallery',
    tabCatalog: 'Catalog',
    tabBooks: 'Books',
    artLoading: 'Loading data...',
    artNotFound: 'Data not found.',
    artBack: 'Back',
    artNoDesc: 'There is no description for this historical heritage yet.',
    artLocationNotMarked: 'Location not marked',
    artUnknownYear: 'Unknown',
    artOpenStatus: 'Available at Storage / Museum',
    artOpen24H: 'Open 24 Hours (Public Area)',
    artOpenSchedule: 'Open According to Operational Schedule',
    artDescTitle: 'Description',
    artReadMore: 'Read More',
    artHide: 'Hide',
    artInfoTitle: 'Information',
    artType: 'Type',
    artYear: 'Year',
    artAuthor: 'Author',
    artLocation: 'Location',
    artCoordsAvailable: 'Coordinates Available',
    artAudioSection: '🎵 Syair & Audio',
    artMapSection: 'Location Map',
    artOpenMap: 'Open in Map',
    artPhotoGallery: 'Photo Gallery',
    artPhotos: '{count} photos',
    artGalleryMedia: 'Gallery & Media',
    artEmptyGallery: 'No photos or audio available for this artifact yet',
    artRelated: 'Related Heritage',

    helpCenterTitle: 'Help Center',
    helpHeroTitle: 'How can we help you?',
    helpHeroSub: 'Find answers to your questions below or contact admin support.',
    helpSearchPlaceholder: 'Search for help...',
    helpCatAll: 'All',
    helpCatGeneral: 'General',
    helpCatAccount: 'Account',
    helpCatBooks: 'Books',
    helpCatGallery: 'Gallery',
    helpPopular: 'Popular Questions',
    helpEmpty: 'No questions found.',
    helpContactTitle: 'Still need help?',
    helpContactSub: 'Contact our admin center directly through the channels below.',
    faq1Q: 'How do I edit my profile?',
    faq1A: "Go to the Profile page, tap the 'Edit Profile' button at the top, then enter your new full name, phone number, or bio and tap 'Save Changes'.",
    faq2Q: 'Why are heritage images/audio not loading?',
    faq2A: 'Make sure your internet connection is stable. The RAHVerse app loads media directly from the Supabase cloud database. If the issue persists, please clear the app cache or restart your device.',
    faq3Q: 'How do I read digital books on RAHVerse?',
    faq3A: "Go to the 'Books' tab, tap the book you want to read, then tap the 'Read Book' button to open our built-in PDF viewer.",
    faq4Q: 'Is the RAHVerse app free to use?',
    faq4A: 'Yes, the RAHVerse app is completely free and is intended for educational purposes, cultural preservation, and maritime tourism in the Archipelago.',
    faq5Q: 'How do I change my account password?',
    faq5A: "Go to the Profile page, tap the 'Change Password' button, enter your old password along with the new password you want to create, then press 'Update Password'.",

    termsHeaderTitle: 'Terms & Conditions',
    termsTitle: 'Usage Policy',
    termsLastUpdated: 'Last updated: June 6, 2026',
    termsIntro: 'Welcome to RAHVerse! This Terms & Conditions page governs your access and use of the RAHVerse mobile application (hereinafter referred to as the "App").',
    termsS1Title: '1. App Usage',
    termsS1Desc: 'The RAHVerse App is provided solely for cultural education, preservation of maritime heritage, and navigation/tourism. You agree to use this app wisely and comply with the applicable laws in Indonesia.',
    termsS2Title: '2. Account & Data Security',
    termsS2Desc: 'When you register or use your account on RAHVerse, you are fully responsible for the confidentiality of your login credentials. Our database uses industry-standard encryption (Supabase Auth) to ensure the protection of your personal data.',
    termsS3Title: '3. Intellectual Property Rights',
    termsS3Desc: 'All content contained in this app, including but not limited to heritage data, historical articles, digital books (PDFs), audio recordings/folk songs, and graphic design interfaces are the property of RAHVerse or licensed contributors.',
    termsS4Title: '4. Privacy Policy',
    termsS4Desc: 'We do not sell or share your personal profile data (such as full name, phone number, and bio) to third parties. This data is used purely for personalizing the RAHVerse browsing experience.',
    termsS5Title: '5. Service Modification & Updates',
    termsS5Desc: 'We reserve the right to modify or discontinue any or all features of the app at any time without prior notice for better system updates and security.',
    termsFootnote: 'By using the RAHVerse App, you are deemed to have agreed to all the terms stated above. If you do not agree to these terms, you are welcome to not use this app.',

    infoHeaderTitle: 'App Information',
    infoVersion: 'Version 1.0.0 (Build 26)',
    infoTagline: 'Cultural Heritage & Maritime Legacy of the Archipelago',
    infoLabelDev: 'Developer',
    infoValueDev: 'RAHVerse Team',
    infoLabelRelease: 'First Release',
    infoValueRelease: 'June 2026',
    infoLabelFramework: 'Framework',
    infoLabelDB: 'Cloud Database',
    infoCopyright: '© 2026 RAHVerse. All Rights Reserved.',
    infoSubCopyright: 'Made with love for Indonesian maritime heritage.',

    adminPanel: 'Admin Panel',
    adminExit: 'Exit',
    adminAdd: 'Add Data',
    adminSave: 'Save Changes',
    adminCancel: 'Cancel',
    adminDelete: 'Delete',
    adminEdit: 'Edit',
    adminConfirmDel: 'Are you sure you want to delete this data?',
    adminSuccess: 'Success',
    adminError: 'Error',
    adminLoading: 'Loading data...',
    adminEmpty: 'No data found',
    adminSearch: 'Search data...',

    notifTitle: 'Notifications',
    notifLoading: 'Loading notifications...',
    notifEmptyTitle: 'No notifications yet',
    notifEmptyDesc: 'All updates from admin will appear here.',
    notifDelete: 'Delete',
    notifClearAlertTitle: 'Clear Notifications',
    notifClearAlertDesc: 'Delete all these notifications from your screen?',
    notifClearCancel: 'Cancel',
    notifClearConfirm: 'Yes, Clear All',
    notifJustNow: 'Just now',
    notifMinutesAgo: 'minutes ago',
    notifHoursAgo: 'hours ago',
    notifDaysAgo: 'days ago',

    resetTitle: 'New Password',
    resetSub: 'Please enter a new password for your account.',
    resetNewPass: 'New password',
    resetConfirmPass: 'Confirm password',
    resetSaveBtn: 'Save Password',
    resetErrEmpty: 'All fields are required.',
    resetErrMatch: 'Passwords do not match.',
    resetErrLength: 'Password must be at least 6 characters.',
    resetSuccessTitle: 'Success!',
    resetSuccessDesc: 'Your password has been successfully updated. Please log in with your new password.',
    resetFailTitle: 'Error',

    profModalEditTitle: 'Edit Profile',
    profModalFullName: 'Full Name',
    profModalFullNamePlaceholder: 'Enter your full name...',
    profModalPhone: 'Phone Number',
    profModalPhonePlaceholder: 'Enter active phone number...',
    profModalBio: 'Short Information (Bio)',
    profModalBioPlaceholder: 'Add a short bio...',
    profModalSave: 'Save Changes',
    profModalPassTitle: 'Update Password',
    profModalOldPass: 'Old Password',
    profModalOldPassPlaceholder: 'Enter current password...',
    profModalNewPass: 'New Password',
    profModalNewPassPlaceholder: 'Enter new password...',
    profModalConfirmPass: 'Confirm New Password',
    profModalConfirmPassPlaceholder: 'Re-enter new password...',
    profModalPassUpdate: 'Update Password',

    loginTabIn: 'Sign In',
    loginTabUp: 'Sign Up',
    loginErrEmailPass: 'Email and password are required.',
    loginErrAllField: 'All fields are required.',
    loginErrMatch: 'Passwords do not match.',
    loginErrLength: 'Password must be at least 6 characters.',
    loginRegSuccessTitle: 'Registration Successful!',
    loginRegSuccessDesc: 'Account created successfully. Please check your email for confirmation, then log in.',
    loginResetReq: 'Please enter your email address to reset your password.',
    loginResetSentTitle: 'Email Sent',
    loginResetSentDesc: 'A password reset link has been sent. Please check your email.',
    
    loginErrInvalidCred: 'Invalid email or password.',
    loginErrNotConf: 'Email not confirmed. Please check your inbox.',
    loginErrAlreadyReg: 'This email is already registered. Please sign in.',
    loginErrWeakPass: 'Password is too weak.',
    loginErrInvalidEmail: 'Invalid email format.',
    loginErrNotFound: 'Email is not registered in our system.',
    
    loginWelcome: 'Welcome Back,',
    loginWelcomeSub: 'Sign in to continue',
    loginJoin: 'Join RAHVerse,',
    loginJoinSub: 'Create a new account to start',
    
    loginFullName: 'Full Name',
    loginFullNamePlace: 'Enter full name...',
    loginEmail: 'Email Address',
    loginEmailPlace: 'example@email.com',
    loginPass: 'Password',
    loginPassPlace: 'Enter password...',
    loginConfirmPass: 'Confirm Password',
    loginConfirmPassPlace: 'Re-enter password...',
    
    loginForgot: 'Forgot password?',
    loginGuest: 'Continue as Guest',

    loginWelcome2: 'Welcome Back',
    loginWelcomeSub2: 'Sign in to access historical manuscript collections.',
    loginJoin2: 'Create New Account',
    loginJoinSub2: 'Join and explore Malay cultural heritage.',
    loginFullName2: 'Full Name',
    loginEmail2: 'Email Address',
    loginPass2: 'Password',
    loginConfirmPass2: 'Confirm Password',
    loginSubmitIn: 'Sign In',
    loginSubmitUp: 'Register Now',
    loginOr: 'OR',

    galTitle: 'Visual Gallery',
    galSub: 'Explore an immersive visualization of Malay heritage.',
    galSearch: 'Search collections...',
    galTabAll: 'All',
    galTabVisual: 'Visuals',
    galTabMusic: 'Music',
    galExplore: 'Deep Exploration',
    galLatest: 'Latest Collections',
    galEmptyTitle: 'No Collections',
    galEmptyDesc: 'There are no gallery collections in RAHVerse yet.',
    galNoDesc: 'No description available for this photo.',
    galNoDescVideo: 'No description available for this video.',
    galDescLbl: 'Description',
    galTypePhoto: 'Photo',
    galTypeVideo: 'Video',
    galTypeMusic: 'Music',
    galUntitled: 'Untitled',
    galZoomBtn: 'Zoom',

    galVideoPlayer: 'Video Player',
    galWatchYT: 'Watch on YouTube',
    galYTAlert: 'This video is from YouTube and restricted from playing inside the app.',
    galPresentTime: 'Present Day',

    
    // Music Player Modal
    galPlayNow: 'Listen Now',
    galLyrics: 'Audio Lyrics',
    galAbout: 'About Artifact',
    galNext: 'Play Next',
    galNoAudio: 'No audio related to this artifact yet.',
    galExploreArtifact: 'Explore This Artifact',
    galAnalyzedAI: 'Analyzed by AI',
    galAnalyzedDesc: 'AI explanation regarding the context of the audio lyrics.',
    galExplanation: 'In-Depth Explanation',










  }
};

const LanguageContext = createContext<LanguageContextType>({
  language: 'id',
  setLanguage: () => {},
  t: (key) => key,
});

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguageState] = useState<LanguageType>('id');

  useEffect(() => {
    AsyncStorage.getItem('user_language').then((saved) => {
      if (saved === 'en' || saved === 'id') {
        setLanguageState(saved as LanguageType);
      }
    });
  }, []);

  const setLanguage = async (lang: LanguageType) => {
    setLanguageState(lang);
    await AsyncStorage.setItem('user_language', lang);
  };

  const t = (key: string): string => {
    // @ts-ignore
    const dict = translations[language] || translations['id'];
    // @ts-ignore
    return dict[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
